FROM nvidia/cuda:11.3.1-devel-ubuntu20.04
RUN mkdir -p /workspace

COPY source/ubuntu-20.04/sources.list /etc/apt/sources.list
RUN apt-get update \
    && apt-get install -y libgl1-mesa-glx build-essential wget git curl libsm6 libxrender1 \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install anaconda
RUN curl http://192.168.22.208:8000/docker-building-files/anaconda/Anaconda3-2021.05-Linux-x86_64.sh --output anaconda.sh
RUN /bin/bash anaconda.sh -b -p /opt/conda \
    && ln -s /opt/conda/etc/profile.d/conda.sh /etc/profile.d/conda.sh \
    && echo ". /opt/conda/etc/profile.d/conda.sh" >> ~/.bashrc \
    && echo "conda activate base" >> ~/.bashrc \
    && find /opt/conda/ -follow -type f -name '*.a' -delete \
    && find /opt/conda/ -follow -type f -name '*.js.map' -delete \
    && /opt/conda/bin/conda clean -afy
RUN rm anaconda.sh

ENV PATH=/opt/conda/bin:$PATH
ENV CUDA_HOME=/usr/local/cuda
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple
COPY source/conda/condarc /root/.condarc

# prepare s3cmd
RUN pip install --no-cache-dir s3cmd==2.3.0

# install pytorch
RUN curl http://192.168.22.208:8000/docker-building-files/python-packages/torch-1.11.0+cu113-cp38-cp38-linux_x86_64.whl --output torch-1.11.0+cu113-cp38-cp38-linux_x86_64.whl
RUN curl http://192.168.22.208:8000/docker-building-files/python-packages/torchvision-0.12.0+cu113-cp38-cp38-linux_x86_64.whl --output torchvision-0.12.0+cu113-cp38-cp38-linux_x86_64.whl
RUN pip install --no-cache-dir torch-1.11.0+cu113-cp38-cp38-linux_x86_64.whl torchvision-0.12.0+cu113-cp38-cp38-linux_x86_64.whl
RUN pip install --no-cache-dir torchaudio==0.11.0
RUN rm torch-1.11.0+cu113-cp38-cp38-linux_x86_64.whl torchvision-0.12.0+cu113-cp38-cp38-linux_x86_64.whl

# install other dependencies
RUN pip install --no-cache-dir easydict==1.9 \
    pyyaml==5.4.1  \
    deprecated==1.2.13 \
    tensorboard==2.10.0 \
    tensorboardX==2.4.1 \
    termcolor==1.1.0 \
    loguru==0.7.2 \
    tqdm==4.59.0 \
    opencv-python==4.2.0.34 \
    pandas==1.2.4 \
    scipy==1.5.4 \
    rasterio==1.2.10 \
    matplotlib==3.3.4 \
    scikit-image==0.18.1 \
    scikit-learn==0.24.1 \
    numba==0.56.4 \
    efficientnet_pytorch==0.7.1 \
    thop==0.0.31.post2005241907 \
    sympy==1.8 \
    terminaltables==3.1.10 \
    addict==2.4.0 \
    cython==0.29.23 \
    pyquaternion==0.9.9 \
    cvxpy==1.2.2 \
    open3d==0.14.1 \
    setuptools==65.6.3 \
    rlanutils==0.1.7

RUN pip install --no-cache-dir pycocotools==2.0.5

# prepare pytorch resnet-18 pretrain model
RUN mkdir -p /root/.cache/torch/hub/checkpoints
RUN curl http://192.168.22.208:8000/docker-building-files/checkpoints/resnet18-f37072fd.pth --output /root/.cache/torch/hub/checkpoints/resnet18-5c106cde.pth

# install s5cmd
RUN curl http://192.168.22.208:8000/docker-building-files/s5cmd/s5cmd_2.2.2_linux_amd64.deb --output s5cmd_2.2.2_linux_amd64.deb
RUN dpkg -i s5cmd_2.2.2_linux_amd64.deb

# install s3fs
ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update \
    && apt-get install -y s3fs \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# install multirun
RUN wget -c https://github.com/nicolas-van/multirun/releases/download/1.1.3/multirun-x86_64-linux-gnu-1.1.3.tar.gz -O - | tar -xz && mv multirun /bin

WORKDIR /workspace

CMD [ "/bin/bash"  ]
